services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: chdb
      MARIADB_USER: ch
      MARIADB_PASSWORD: ch
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080

volumes:
  db-data:
