"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.defaultCat = exports.descriptors = void 0;
exports.descriptors = {
    duration: "",
    gender: "",
    coatColour: "",
    coatLength: "",
    cut: "false",
    appearance: "",
    issues: "",
    history: "",
    procedures: "",
    characteristics: [],
    likes: [],
    cat: [],
    descriptionOfCharacter: "",
    treatOtherCats: "",
    treatDogs: "",
    treatChildren: "",
    outdoorsIndoors: "",
    other: "",
    wishes: "",
};
exports.defaultCat = {
    ...exports.descriptors,
    title: "",
    description: "",
    name: "",
    birthDate: null,
    currentLoc: "",
    age: "",
    chipNr: "",
    llr: "false",
    genderLabel: "",
    wormMedName: "",
    wormMedDate: null,
    rescueDate: null,
    foundLoc: "",
    vacc: null,
    vaccEnd: null,
    rabiesVacc: null,
    rabiesVaccEnd: null,
    images: [],
    other: "",
    wishes: "",
    driveId: "",
};
