export const MULTISELECT_FIELD_VALUES = {
  personality: [
    'Julge',
    'Arg',
    'Aktiivne',
    'Väga aktiivne',
    'Rahulik',
    'Sõbralik',
    'Pahur',
    'Hellik',
    'Ei lase puudutada ennast',
    'Seltsiv',
    'Omaette hoidev',
    'Hea isuga',
    'Uudishimulik',
    'Mänguline',
    'Stressis',
    'Õrnahingeline',
    'Rahumeelne',
    'Isekas',
    'Sisiseb palju',
  ],
  likes: [
    'Süles olla',
    'Kaisus magada',
    'Pai saada',
    'Palju tähelepanu',
    'Mängida mänguasjadega inimesega',
    'Mängida mänguasjadega üksinda',
  ],
  behaviorTraits: [
    'Kasutab liivakasti hästi',
    'Kasutab kratsimispuud hästi',
    'On valikuline toiduga, pirtsutab',
    'Harjub kiirelt uue kohaga',
    'Kipub kratsima muud mööblit',
    'Usaldab inimesi kiiresti',
  ],
};

export const FIELD_VALUES = {
  attitudeTowardsCats: [
    'Meeldivad väga, vajab kindlasti kõrvale kassi',
    'Meeldivad',
    'Neutraalselt',
    'Umbusklik',
    'Ei meeldi',
    'Ei ole tutvunud teiste kassidega',
    'Peab olema ainus kass peres',
  ],
  attitudeTowardsDogs: [
    'Jumaldab koeri, tahaks väga koertega koju saada',
    'Saab koertega hästi läbi',
    'Neutraalselt',
    'Umbusklik',
    'Ei meeldi',
    'Pole tutvunud',
  ],
  attitudeTowardsChildren: [
    'Hästi',
    'Neutraalselt',
    'Umbusklik',
    'Ei sobi lastega',
    'Ei ole kohanud lapsi, ei tea',
  ],
  suitabilityForIndoorOrOutdoor: [
    'Toakassiks',
    'Õuekassiks',
    'Toa- ja õuekassiks',
  ],
};

export const COAT_COLOURS = [
  'Triibik',
  'Triibik valgega',
  'Must',
  'Must-valge',
  'Kilpkonn',
  'Kolmevärviline',
  'Punane',
  'Punane valgega',
  'Valge',
  'Hall',
  'Hall triibik',
  'Hall triibik valgega',
  'Hall valgega',
  'Helehall',
  'Colorpoint',
  'Siiamilaadne',
  'Punane (beež)',
];

export const COAT_LENGTHS = [
  'Lühikarvaline',
  'Poolpikk karvaline',
  'Pikakarvaline',
];
