version: '3.8'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: chdb
      MARIADB_USER: ch
      MARIADB_PASSWORD: ch
    ports:
      - 3306:3306
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d  # Mount the init-db directory
      #- db-data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  db-data:
  redis-data:
#volumes:
#  db-data:
