name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      APP_ROOT: /data01/virt133730/domeenid/www.catshelp.ee
      # RELEASES_DIR: /data01/virt133730/domeenid/www.catshelp.ee/liides/releases

    steps:
      - name: 🧾 Checkout repository
        uses: actions/checkout@v3

      - name: 📦 Install dependencies
        run: npm install

      - name: 🏗️ Build frontend & backend
        env:
          VITE_BACKEND_URL: ${{ vars.VITE_BACKEND_URL }}
          VITE_FRONTEND_URL: ${{ vars.VITE_FRONTEND_URL }}
          VITE_GOOGLE_CLIENT_ID: ${{ vars.VITE_GOOGLE_CLIENT_ID }}
        run: npm run build

      - name: 📁 Prepare release archive
        run: |
          TIMESTAMP=$(date +%Y.%m.%d-%H.%M.%S)
          GIT_SHA=$(git rev-parse --short HEAD)
          RELEASE_NAME=$TIMESTAMP-$GIT_SHA
          echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV
          cd apps/server
          tar -czf $RELEASE_NAME.tar.gz .

      - name: 📤 Upload release to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.CATSHELP_SSH_KEY }}
          port: 22
          source: "${{ env.RELEASE_NAME }}.tar.gz"
          target: "${{ env.APP_ROOT }}/liides"

      - name: 🚀 Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.CATSHELP_SSH_KEY }}
          port: 22
          script: |
            set -e

            cd ${{ env.APP_ROOT }}/htdocs/liides
            mv credentials.json ${{ env.APP_ROOT }}/liides
            mv oauth.json ${{ env.APP_ROOT }}/liides
            mv .env ${{ env.APP_ROOT }}/liides
            mv storage ${{ env.APP_ROOT }}/liides

            rm -rf ./*

            mv ${{ env.APP_ROOT }}/liides/credentials.json .
            mv ${{ env.APP_ROOT }}/liides/oauth.json .
            mv ${{ env.APP_ROOT }}/liides/.env .
            mv ${{ env.APP_ROOT }}/liides/storage .
            mv ${{ env.APP_ROOT }}/liides/${{ env.RELEASE_NAME }}.tar.gz .

            tar -xzf ${{ env.RELEASE_NAME }}.tar.gz
            rm ${{ env.RELEASE_NAME }}.tar.gz

            composer update

            # Run migrations
            php artisan migrate

            echo "✅ Deployed ${{ env.RELEASE_NAME }} successfully"
